[package]
name = "kaolin"
version = "0.1.0"
edition = "2024"

[dependencies]
derive_builder = "0.20.2"
syn = {version = "2.0.104", features = ["full", "parsing"]}
derive-declare = { path = "../derive-declare" }
raylib = "5.5.1"

[dependencies.uuid]
version = "1.17.0"
features = ["v4"]